### ISSUE TITLE
Module does not surface dependency errors

### ISSUE THREAD

**Issue by software-opal** [JakeBecker/ide-elixir#24]
Using the language server on a clean repo gives me this error in the JS console. It would be good to surface it to the user so they know about it.

```
Elixir (ElixirLS) rpc.sendRequest textDocument/formatting threw ResponseError: an exception was raised:
    ** (Mix.Error) Unavailable dependency :phoenix given to :import_deps in the formatter configuration. The dependency cannot be found in the file system, please run "mix deps.get" and try again
        (mix 1.10.2) lib/mix.ex:392: Mix.raise/1
        (mix 1.10.2) lib/mix/tasks/format.ex:246: anonymous fn/3 in Mix.Tasks.Format.eval_deps_opts/2
        (elixir 1.10.2) lib/enum.ex:2111: Enum."-reduce/3-lists^foldl/2-0-"/3
        (mix 1.10.2) lib/mix/tasks/format.ex:245: Mix.Tasks.Format.eval_deps_opts/2
        (mix 1.10.2) lib/mix/tasks/format.ex:201: anonymous fn/5 in Mix.Tasks.Format.eval_deps_and_subdirectories/4
        (mix 1.10.2) lib/mix/tasks/format.ex:276: anonymous fn/2 in Mix.Tasks.Format.eval_subs_opts/3
        (elixir 1.10.2) lib/enum.ex:1094: anonymous fn/3 in Enum.flat_map_reduce/3
        (elixir 1.10.2) lib/enum.ex:3686: Enumerable.List.reduce/3
    at handleResponse (/Users/opalsymes/.atom/packages/ide-elixir/node_modules/vscode-jsonrpc/lib/main.js:436:48)
    at processMessageQueue (/Users/opalsymes/.atom/packages/ide-elixir/node_modules/vscode-jsonrpc/lib/main.js:263:17)
    at Immediate.setImmediate (/Users/opalsymes/.atom/packages/ide-elixir/node_modules/vscode-jsonrpc/lib/main.js:247:13)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```

**Comment by software-opal** [comment]
It turns out that the error is because I needed to fix some configuration that was throwing an error.
